# ============================================================
# FILE: engine/joseph_brain/__init__.py
# PURPOSE: Backward-compatible re-exports for the joseph_brain package.
#          All existing imports like `from engine.joseph_brain import X`
#          continue to work unchanged.
# ============================================================
from engine.joseph_brain._monolith import (
    # ── Public Functions ────────────────────────────────────────
    build_joseph_rant,
    build_joseph_top_pick_take,
    build_rant,
    determine_verdict,
    joseph_ambient_line,
    joseph_analyze_game,
    joseph_analyze_pick,
    joseph_analyze_player,
    joseph_auto_log_bets,
    joseph_blowout_warning,
    joseph_commentary,
    joseph_commentary_for_stat,
    joseph_compare_props,
    joseph_evaluate_parlay,
    joseph_full_analysis,
    joseph_generate_best_bets,
    joseph_generate_full_slate_analysis,
    joseph_generate_independent_picks,
    joseph_get_ambient_context,
    joseph_god_mode_lineup,
    joseph_god_mode_player,
    joseph_god_mode_prospect,
    joseph_god_mode_trade,
    joseph_gut_call,
    joseph_platinum_lock,
    joseph_quick_take,
    joseph_rank_picks,
    joseph_vault_reaction,
    reset_fragment_state,
    # ── Tournament Commentary Functions ────────────────────────
    joseph_tournament_preview,
    joseph_tournament_overpriced_call,
    joseph_tournament_sleeper_pick,
    joseph_tournament_ownership_reaction,
    joseph_tournament_score_reaction,
    joseph_tournament_championship_play_by_play,
    # ── Constants ───────────────────────────────────────────────
    AMBIENT_CONTEXT_POOL,
    AMBIENT_POOLS,
    BODY_TEMPLATES,
    ELIMINATION_GAME_TEMPLATES,
    FINALS_TEMPLATES,
    GAME_SEVEN_TEMPLATES,
    CATCHPHRASE_POOL,
    CLOSER_POOL,
    COMMENTARY_OPENER_POOL,
    DATA_BODY_TEMPLATES,
    DAWG_FACTOR_TABLE,
    GOD_MODE_MODULES,
    JOSEPH_COMPS_DATABASE,
    JOSEPH_CONFIG,
    MARKET_CONSENSUS_MIN_BOOKS,
    MARKET_HIGH_TOTAL_THRESHOLD,
    MARKET_LOW_TOTAL_THRESHOLD,
    OPENER_POOL,
    PIVOT_POOL,
    PLAYOFF_BODY_TEMPLATES,
    PLAYOFF_CLOSER_POOL,
    PLAYOFF_OPENER_POOL,
    STAT_BODY_TEMPLATES,
    SERIES_CLINCH_TEMPLATES,
    STAT_COMMENTARY_POOL,
    TICKET_NAMES,
    VERDICT_EMOJIS,
    VERDICT_THRESHOLDS,
    # ── Tournament Fragment Pools ──────────────────────────────
    TOURNAMENT_PREVIEW_POOL,
    TOURNAMENT_OWNERSHIP_REACTION_POOL,
    TOURNAMENT_RESULTS_POOL,
    TOURNAMENT_BUST_POOL,
    TOURNAMENT_SLEEPER_HIT_POOL,
    TOURNAMENT_CHAMPIONSHIP_POOL,
    # ── Private functions (imported by tests) ──────────────────
    _build_data_sentences,
    _compute_hit_rate,
    _compute_recent_trend,
    _extract_edge,
    _extract_home_away_splits,
    _generate_counter_argument,
    _get_player_db_intel,
    _get_team_db_intel,
    _joseph_answer_question,
    _pick_ambient,
    _pick_commentary,
    _pick_fragment,
    _select_fragment,
    _SHORT_TAKE_TEMPLATES,
    _STAT_CATEGORY_MAP,
    _STAT_DB_KEY_MAP,
    BLOWOUT_DIFFERENTIAL_MILD,
    BLOWOUT_DIFFERENTIAL_HEAVY,
)

# Re-export fragment state from fragments module
from engine.joseph_brain.fragments import _used_fragments, _used_ambient, _used_commentary  # noqa: F401

__all__ = [
    # Public functions
    "build_joseph_rant",
    "build_joseph_top_pick_take",
    "build_rant",
    "determine_verdict",
    "joseph_ambient_line",
    "joseph_analyze_game",
    "joseph_analyze_pick",
    "joseph_analyze_player",
    "joseph_auto_log_bets",
    "joseph_blowout_warning",
    "joseph_commentary",
    "joseph_commentary_for_stat",
    "joseph_compare_props",
    "joseph_evaluate_parlay",
    "joseph_full_analysis",
    "joseph_generate_best_bets",
    "joseph_generate_full_slate_analysis",
    "joseph_generate_independent_picks",
    "joseph_get_ambient_context",
    "joseph_god_mode_lineup",
    "joseph_god_mode_player",
    "joseph_god_mode_prospect",
    "joseph_god_mode_trade",
    "joseph_gut_call",
    "joseph_platinum_lock",
    "joseph_quick_take",
    "joseph_rank_picks",
    "joseph_vault_reaction",
    "reset_fragment_state",
    # Tournament commentary functions
    "joseph_tournament_preview",
    "joseph_tournament_overpriced_call",
    "joseph_tournament_sleeper_pick",
    "joseph_tournament_ownership_reaction",
    "joseph_tournament_score_reaction",
    "joseph_tournament_championship_play_by_play",
    # Constants
    "AMBIENT_CONTEXT_POOL",
    "AMBIENT_POOLS",
    "BODY_TEMPLATES",
    "ELIMINATION_GAME_TEMPLATES",
    "FINALS_TEMPLATES",
    "GAME_SEVEN_TEMPLATES",
    "CATCHPHRASE_POOL",
    "CLOSER_POOL",
    "COMMENTARY_OPENER_POOL",
    "DATA_BODY_TEMPLATES",
    "DAWG_FACTOR_TABLE",
    "GOD_MODE_MODULES",
    "JOSEPH_COMPS_DATABASE",
    "JOSEPH_CONFIG",
    "MARKET_CONSENSUS_MIN_BOOKS",
    "MARKET_HIGH_TOTAL_THRESHOLD",
    "MARKET_LOW_TOTAL_THRESHOLD",
    "OPENER_POOL",
    "PIVOT_POOL",
    "PLAYOFF_BODY_TEMPLATES",
    "PLAYOFF_CLOSER_POOL",
    "PLAYOFF_OPENER_POOL",
    "STAT_BODY_TEMPLATES",
    "SERIES_CLINCH_TEMPLATES",
    "STAT_COMMENTARY_POOL",
    "TICKET_NAMES",
    "VERDICT_EMOJIS",
    "VERDICT_THRESHOLDS",
    # Tournament fragment pools
    "TOURNAMENT_PREVIEW_POOL",
    "TOURNAMENT_OWNERSHIP_REACTION_POOL",
    "TOURNAMENT_RESULTS_POOL",
    "TOURNAMENT_BUST_POOL",
    "TOURNAMENT_SLEEPER_HIT_POOL",
    "TOURNAMENT_CHAMPIONSHIP_POOL",
]
